version: "3.0"

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:

networks:
  default:
    driver: bridge
